name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production  # lie le job à ton environnement

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "Déploiement de l’image ghcr.io/Bakary923/cicd-bakary:${{ github.ref_name }} sur production..."
          echo "App secret = $APP_SECRET"
