name: Deploy to Production (simulated)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (ex: v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      # url: https://your.production.url  # opcionnel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show secret from environment (masked)
        run: |
          echo "Using APP_SECRET from environment (masked) -> ${{ secrets.APP_SECRET }}"
      - name: Simulate deployment
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.repository.name }}:${{ inputs.image_tag }}"
          echo "Déploiement de l'image $IMAGE sur production..."
          # Ici on simule : on pourrait appeler kubectl, ssh, etc.
