name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    environment:
      name: production   #  C’est ce qui va “lier” ton environnement
      url: https://example.com/  # Optionnel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Déploiement
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "Déploiement de l’image ghcr.io/Bakary923/ci-cd_bakary:${{ github.ref_name }} sur production..."
          echo "App secret = $APP_SECRET"
