name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate Deployment
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "✅ Déploiement simulé de l’image ghcr.io/Bakary923/ci-cd_bakary:${{ github.ref_name }} sur production..."
          echo "App secret = $APP_SECRET"
          sleep 10  # permet de “voir” le job en cours
