name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*.*.*'   # Déclenchement uniquement sur les tags (ex : v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # Nécessaire pour publier sur GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}
